# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import analysis_pb2 as analysis__pb2
import grpc

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in analysis_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AnalysisServiceStub:
    """Analysis Service - implemented by both LLM Chain and CLI Agent"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeMarket = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/AnalyzeMarket",
            request_serializer=analysis__pb2.MarketAnalysisRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.QuickAnalysis = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/QuickAnalysis",
            request_serializer=analysis__pb2.QuickAnalysisRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.ScanMarkets = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/ScanMarkets",
            request_serializer=analysis__pb2.MarketScanRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.AssessRisk = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/AssessRisk",
            request_serializer=analysis__pb2.RiskAssessmentRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.GenerateTradePlan = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/GenerateTradePlan",
            request_serializer=analysis__pb2.TradePlanRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeMarketStream = channel.unary_stream(
            "/polymarket.analysis.AnalysisService/AnalyzeMarketStream",
            request_serializer=analysis__pb2.MarketAnalysisRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisChunk.FromString,
            _registered_method=True,
        )
        self.AnalyzeTrader = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/AnalyzeTrader",
            request_serializer=analysis__pb2.TraderAnalysisRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.EvaluateCopyTrade = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/EvaluateCopyTrade",
            request_serializer=analysis__pb2.CopyTradeEvaluationRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.EvaluateInversePosition = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/EvaluateInversePosition",
            request_serializer=analysis__pb2.InversePositionEvaluationRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeSentiment = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/AnalyzeSentiment",
            request_serializer=analysis__pb2.SentimentAnalysisRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.DiscoverBestTrade = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/DiscoverBestTrade",
            request_serializer=analysis__pb2.DiscoverBestTradeRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.IndexMarketsRAG = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/IndexMarketsRAG",
            request_serializer=analysis__pb2.IndexMarketsRAGRequest.SerializeToString,
            response_deserializer=analysis__pb2.AnalysisResponse.FromString,
            _registered_method=True,
        )
        self.GenerateNews = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/GenerateNews",
            request_serializer=analysis__pb2.GenerateNewsRequest.SerializeToString,
            response_deserializer=analysis__pb2.GenerateNewsResponse.FromString,
            _registered_method=True,
        )
        self.GenerateNewsBatch = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/GenerateNewsBatch",
            request_serializer=analysis__pb2.GenerateNewsBatchRequest.SerializeToString,
            response_deserializer=analysis__pb2.GenerateNewsBatchResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/polymarket.analysis.AnalysisService/HealthCheck",
            request_serializer=analysis__pb2.HealthRequest.SerializeToString,
            response_deserializer=analysis__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class AnalysisServiceServicer:
    """Analysis Service - implemented by both LLM Chain and CLI Agent"""

    def AnalyzeMarket(self, request, context):
        """Comprehensive market analysis with optional research"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def QuickAnalysis(self, request, context):
        """Quick 2-3 sentence analysis"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ScanMarkets(self, request, context):
        """Scan multiple markets for opportunities"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AssessRisk(self, request, context):
        """Assess risk for a potential trade"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateTradePlan(self, request, context):
        """Generate trade execution plan"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeMarketStream(self, request, context):
        """Streaming analysis for long-running tasks"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeTrader(self, request, context):
        """── NEW: Trader / Copy-Trading RPCs ──────────────────────

        Full trader profile analysis with internet research
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EvaluateCopyTrade(self, request, context):
        """Evaluate whether to copy a specific trade"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EvaluateInversePosition(self, request, context):
        """Evaluate whether an open position should be reversed"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeSentiment(self, request, context):
        """── NEW: Advanced Analysis RPCs ──────────────────────────

        Analyse public sentiment around a market/topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DiscoverBestTrade(self, request, context):
        """Autonomous trade discovery — find the single best trade"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IndexMarketsRAG(self, request, context):
        """Index markets into RAG vector store"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateNews(self, request, context):
        """── NEW: News Generation RPCs ────────────────────────────

        Generate AI news article for a market
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateNewsBatch(self, request, context):
        """Generate news articles for multiple markets (batch)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AnalyzeMarket": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeMarket,
            request_deserializer=analysis__pb2.MarketAnalysisRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "QuickAnalysis": grpc.unary_unary_rpc_method_handler(
            servicer.QuickAnalysis,
            request_deserializer=analysis__pb2.QuickAnalysisRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "ScanMarkets": grpc.unary_unary_rpc_method_handler(
            servicer.ScanMarkets,
            request_deserializer=analysis__pb2.MarketScanRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "AssessRisk": grpc.unary_unary_rpc_method_handler(
            servicer.AssessRisk,
            request_deserializer=analysis__pb2.RiskAssessmentRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "GenerateTradePlan": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateTradePlan,
            request_deserializer=analysis__pb2.TradePlanRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "AnalyzeMarketStream": grpc.unary_stream_rpc_method_handler(
            servicer.AnalyzeMarketStream,
            request_deserializer=analysis__pb2.MarketAnalysisRequest.FromString,
            response_serializer=analysis__pb2.AnalysisChunk.SerializeToString,
        ),
        "AnalyzeTrader": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeTrader,
            request_deserializer=analysis__pb2.TraderAnalysisRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "EvaluateCopyTrade": grpc.unary_unary_rpc_method_handler(
            servicer.EvaluateCopyTrade,
            request_deserializer=analysis__pb2.CopyTradeEvaluationRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "EvaluateInversePosition": grpc.unary_unary_rpc_method_handler(
            servicer.EvaluateInversePosition,
            request_deserializer=analysis__pb2.InversePositionEvaluationRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "AnalyzeSentiment": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeSentiment,
            request_deserializer=analysis__pb2.SentimentAnalysisRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "DiscoverBestTrade": grpc.unary_unary_rpc_method_handler(
            servicer.DiscoverBestTrade,
            request_deserializer=analysis__pb2.DiscoverBestTradeRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "IndexMarketsRAG": grpc.unary_unary_rpc_method_handler(
            servicer.IndexMarketsRAG,
            request_deserializer=analysis__pb2.IndexMarketsRAGRequest.FromString,
            response_serializer=analysis__pb2.AnalysisResponse.SerializeToString,
        ),
        "GenerateNews": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateNews,
            request_deserializer=analysis__pb2.GenerateNewsRequest.FromString,
            response_serializer=analysis__pb2.GenerateNewsResponse.SerializeToString,
        ),
        "GenerateNewsBatch": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateNewsBatch,
            request_deserializer=analysis__pb2.GenerateNewsBatchRequest.FromString,
            response_serializer=analysis__pb2.GenerateNewsBatchResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=analysis__pb2.HealthRequest.FromString,
            response_serializer=analysis__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "polymarket.analysis.AnalysisService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "polymarket.analysis.AnalysisService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AnalysisService:
    """Analysis Service - implemented by both LLM Chain and CLI Agent"""

    @staticmethod
    def AnalyzeMarket(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/AnalyzeMarket",
            analysis__pb2.MarketAnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def QuickAnalysis(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/QuickAnalysis",
            analysis__pb2.QuickAnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ScanMarkets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/ScanMarkets",
            analysis__pb2.MarketScanRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AssessRisk(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/AssessRisk",
            analysis__pb2.RiskAssessmentRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateTradePlan(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/GenerateTradePlan",
            analysis__pb2.TradePlanRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeMarketStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/polymarket.analysis.AnalysisService/AnalyzeMarketStream",
            analysis__pb2.MarketAnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeTrader(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/AnalyzeTrader",
            analysis__pb2.TraderAnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EvaluateCopyTrade(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/EvaluateCopyTrade",
            analysis__pb2.CopyTradeEvaluationRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EvaluateInversePosition(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/EvaluateInversePosition",
            analysis__pb2.InversePositionEvaluationRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeSentiment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/AnalyzeSentiment",
            analysis__pb2.SentimentAnalysisRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DiscoverBestTrade(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/DiscoverBestTrade",
            analysis__pb2.DiscoverBestTradeRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def IndexMarketsRAG(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/IndexMarketsRAG",
            analysis__pb2.IndexMarketsRAGRequest.SerializeToString,
            analysis__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateNews(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/GenerateNews",
            analysis__pb2.GenerateNewsRequest.SerializeToString,
            analysis__pb2.GenerateNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateNewsBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/GenerateNewsBatch",
            analysis__pb2.GenerateNewsBatchRequest.SerializeToString,
            analysis__pb2.GenerateNewsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/polymarket.analysis.AnalysisService/HealthCheck",
            analysis__pb2.HealthRequest.SerializeToString,
            analysis__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
